name = "killergg/jecs_refs"
version = "0.1.0"
description = "A table of refs to be used by jecs packages"
authors = ["NeonD00m"]
repository = "https://github.com/NeonD00m/jecs_std"
license = "MIT"

includes = [
  "pesde.toml",
  "LICENSE",
  "src",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

