name = "killergg/jecs_std"
version = "0.1.8"
description = "A standard library for jecs"
authors = ["NeonD00m", "as8d", "Ukendio"]
repository = "https://github.com/NeonD00m/jecs_std"
license = "MIT"

includes = [
  "pesde.toml",
  "LICENSE",
  "src",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
jecs = { name = "marked/jecs", version = "^0.6.0" }
world = { workspace = "killergg/jecs_world", version = "^", target = "roblox" }
ref = { workspace = "killergg/jecs_ref", version = "^", target = "roblox" }
refs = { workspace = "killergg/jecs_refs", version = "^", target = "roblox" }
reverseRef = { workspace = "killergg/jecs_reverse_ref", version = "^", target = "roblox" }
throttle = { workspace = "killergg/jecs_throttle", version = "^", target = "roblox" }
interval = { workspace = "killergg/jecs_interval", version = "^", target = "roblox" }
collect = { workspace = "killergg/jecs_collect", version = "^", target = "roblox" }
handle = { workspace = "killergg/jecs_handle", version = "^", target = "roblox" }
observers = { workspace = "killergg/jecs_observers", version = "^", target = "roblox" }